# Generated by Django 3.0.3 on 2020-02-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('satisfaction', models.IntegerField(blank=True, default=10)),
                ('user_img', models.CharField(blank=True, max_length=300)),
                ('total_cost', models.FloatField(blank=True, default=0)),
                ('likes', models.CharField(blank=True, max_length=350)),
                ('num_of_subs', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('billing_period', models.CharField(choices=[('Daily', 'Billed everyday'), ('Weekly', 'Billed weekly'), ('Bi-Weekly', 'Billed every two weeks'), ('Monthly', 'Billed every month'), ('Bi-Monthly', 'Billed every two months'), ('Yearly', 'Billed once a year')], default='Monthly', max_length=30)),
                ('billing_date', models.CharField(default='N/A', max_length=100)),
                ('type_of_service', models.CharField(choices=[('Unsure', 'Not sure'), ('Movies', 'Tailored towards movies'), ('Video Games', 'Tailored towards Video Games'), ('TV/shows', 'Tailored towards Television Shows'), ('Cloud-based services', 'Tailored towards Cloud based data services'), ('Software Services', 'Tailored towards software apps like office'), ('Labor Services', 'Tailored towards physical in person labor services')], default='Unsure', max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('average_rating', models.PositiveIntegerField(default=5)),
                ('user', models.ManyToManyField(related_name='user_subscriptions', to='subscription_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(blank=True, choices=[('1', 'Awful'), ('2', 'Bad'), ('3', 'Ok'), ('4', 'Good'), ('5', 'Excellent')], default='5', max_length=250)),
                ('comment', models.CharField(blank=True, max_length=150)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_reviews', to='subscription_app.Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='subscription_app.User')),
            ],
        ),
    ]
